working_dir: &working_dir ~/app
version: 2.0
#####################################################################################################################################
jobs:
  workspace-full:
    resource_class: medium
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            ls
            docker run -e CI=true abidlo/go:latest
          no_output_timeout: 59m
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/dazzle/
            cp full/*.xml ~/test-results/dazzle
            
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/dazzle
      - persist_to_workspace:
          root: .
          paths:
            - workspace-full.tar

  workspace-full-vnc:
    resource_class: medium
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            ls
            docker run -e CI=true abidlo/go:latest
          no_output_timeout: 58m
      - persist_to_workspace:
          root: .
          paths:
            - workspace-full-vnc.tar

  mdbook:
    resource_class: medium
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            ls
            docker run -e CI=true abidlo/go:latest
          no_output_timeout: 57m

  workspace-dotnet:
    resource_class: medium
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            ls
            docker run -e CI=true abidlo/go:latest
          no_output_timeout: 56m

  workspace-dotnet-vnc:
    resource_class: medium
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            ls
            docker run -e CI=true abidlo/go:latest
          no_output_timeout: 55m

  workspace-postgres:
    resource_class: medium
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            ls
            docker run -e CI=true abidlo/go:latest
          no_output_timeout: 54m

  workspace-mysql:
    resource_class: medium
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            ls
            docker run -e CI=true abidlo/go:latest
          no_output_timeout: 53m

  workspace-mongodb:
    resource_class: medium
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            ls
            docker run -e CI=true abidlo/go:latest
          no_output_timeout: 52m
  workspace-flutter:
    resource_class: medium
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            ls
            docker run -e CI=true abidlo/go:latest
          no_output_timeout: 51m
  workspace-gecko:
    resource_class: medium
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            ls
            docker run -e CI=true abidlo/go:latest
          no_output_timeout: 50m

  workspace-wasm:
    resource_class: medium
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            ls
            docker run -e CI=true abidlo/go:latest
          no_output_timeout: 49m
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - workspace-full
      - workspace-full-vnc
          
      - mdbook
          
      - workspace-dotnet
          
      - workspace-dotnet-vnc
          
      - workspace-postgres
          
      - workspace-mysql
          
      - workspace-mongodb
          
      - workspace-flutter
          
      - workspace-gecko
          
      - workspace-wasm
